In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from kernel import *
import numpy as np
from PDE_solver_backend import FasterGaussianKernel

In [3]:
X=np.random.rand(300,2)
Y=np.random.rand(400,2)

In [4]:
k=Differentiable_matern_kernel(5/2,0.5)


In [5]:
k2 = FasterGaussianKernel(0.5, X, np.empty((0,2)), Y, False)

In [6]:
k2.get_dirac()

array([[1.        , 0.91854796, 0.97983953, ..., 0.31387373, 0.59530925,
        0.28000738],
       [0.91854796, 1.        , 0.82998753, ..., 0.27826448, 0.52523122,
        0.35445665],
       [0.97983953, 0.82998753, 1.        , ..., 0.29172058, 0.56759421,
        0.2208794 ],
       ...,
       [0.31387373, 0.27826448, 0.29172058, ..., 1.        , 0.8797298 ,
        0.68292495],
       [0.59530925, 0.52523122, 0.56759421, ..., 0.8797298 , 1.        ,
        0.63419454],
       [0.28000738, 0.35445665, 0.2208794 , ..., 0.68292495, 0.63419454,
        1.        ]])

In [7]:
k.apply('kappa', X, X)

array([[1.        , 0.68334574, 0.94503662, ..., 0.45013874, 0.74779467,
        0.30931178],
       [0.68334574, 1.        , 0.59585874, ..., 0.16796272, 0.33553121,
        0.12354606],
       [0.94503662, 0.59585874, 1.        , ..., 0.49683735, 0.76876269,
        0.27852109],
       ...,
       [0.45013874, 0.16796272, 0.49683735, ..., 1.        , 0.82503825,
        0.59925797],
       [0.74779467, 0.33553121, 0.76876269, ..., 0.82503825, 1.        ,
        0.55062002],
       [0.30931178, 0.12354606, 0.27852109, ..., 0.59925797, 0.55062002,
        1.        ]])

In [8]:
k.apply('kappa', X, Y)

array([[0.84359043, 0.65835212, 0.85742973, ..., 0.88472845, 0.77366819,
        0.88324121],
       [0.82569672, 0.60639535, 0.91381832, ..., 0.90887071, 0.45159065,
        0.71237926],
       [0.69123786, 0.49951789, 0.73468397, ..., 0.7788728 , 0.91899026,
        0.93523496],
       ...,
       [0.2747652 , 0.24728286, 0.25762423, ..., 0.27228966, 0.51995535,
        0.35344312],
       [0.51338267, 0.44937091, 0.48761648, ..., 0.50895914, 0.71391022,
        0.5891344 ],
       [0.24861959, 0.30660785, 0.20361737, ..., 0.20284312, 0.2327356 ,
        0.18961348]])

In [9]:
k.apply('D_x2_D_y2_kappa', X, Y)

array([[ 3.69742208,  0.2382206 ,  4.73704737, ...,  5.1570024 ,
         1.7397667 ,  3.22239399],
       [ 3.33527109,  0.1107499 ,  5.13466786, ...,  5.35290668,
         1.26316234,  2.79883017],
       [ 1.52985067, -0.76014847,  2.84642841, ...,  3.48528297,
         4.2875577 ,  5.40453562],
       ...,
       [ 0.89171023,  0.41643685,  0.89151553, ...,  0.96455437,
         1.23600516,  1.07358953],
       [ 2.06927479,  0.80908301,  2.08205597, ...,  2.20773087,
         1.07846019,  1.77469721],
       [ 0.52343397,  1.07629638,  0.24506094, ...,  0.15835078,
        -0.91215015, -0.38814836]])

In [10]:
k.kappa(X[0,0],X[0,1],Y[0,0],Y[0,1])

Array(0.84359043, dtype=float64)

In [11]:
from sklearn.gaussian_process.kernels import Matern,RBF
kernel = 1.0 * Matern(length_scale=0.5, nu=5/2)
#kernel=RBF(length_scale=0.5)
kernel(X,Y)

array([[0.84359043, 0.65835212, 0.85742973, ..., 0.88472845, 0.77366819,
        0.88324121],
       [0.82569672, 0.60639535, 0.91381832, ..., 0.90887071, 0.45159065,
        0.71237926],
       [0.69123786, 0.49951789, 0.73468397, ..., 0.7788728 , 0.91899026,
        0.93523496],
       ...,
       [0.2747652 , 0.24728286, 0.25762423, ..., 0.27228966, 0.51995535,
        0.35344312],
       [0.51338267, 0.44937091, 0.48761648, ..., 0.50895914, 0.71391022,
        0.5891344 ],
       [0.24861959, 0.30660785, 0.20361737, ..., 0.20284312, 0.2327356 ,
        0.18961348]])

In [72]:
import PDE_solver_backend

X_int=np.random.rand(1000,2)
X_shared=np.random.rand(340,2)
X_ext=np.random.rand(550,2)



In [74]:
A,B,D=PDE_solver_backend.PDESolver.get_kernel_matrix_fast_gaussian(X_int,X_shared,X_ext,0.1,1e-5,False,True)

In [73]:
A2,B2,D2=PDE_solver_backend.PDESolver.get_kernel_matrix_matern(X_int,X_shared,X_ext,0.1,2.5,1e-5,False,True)

2023-07-06 18:33:10.763230: E external/org_tensorflow/tensorflow/compiler/xla/service/slow_operation_alarm.cc:65] Constant folding an instruction is taking > 1s:

  reduce.49 (displaying the full instruction incurs a runtime overhead. Raise your logging level to 4 or above).

This isn't necessarily a bug; constant-folding is inherently a trade-off between compilation time and speed at runtime.  XLA has some guards that attempt to keep constant folding from taking too long, but fundamentally you'll always be able to come up with an input program that takes a long time.

If you'd like to file a bug, run with envvar XLA_FLAGS=--xla_dump_to=/tmp/foo and attach the results.
2023-07-06 18:33:12.159354: E external/org_tensorflow/tensorflow/compiler/xla/service/slow_operation_alarm.cc:133] The operation took 2.396182s
Constant folding an instruction is taking > 1s:

  reduce.49 (displaying the full instruction incurs a runtime overhead. Raise your logging level to 4 or above).

This isn't nece

In [ ]:
np.linalg.norm(B-B2,np.inf)

9.215970952205541e-09

In [21]:
from tensorflow_probability.substrates.jax.math.psd_kernels import GeneralizedMatern
k=GeneralizedMatern(
    3.4,
    amplitude=None,
    length_scale=0.5,
    inverse_length_scale=None,
    feature_ndims=1,
    validate_args=False,
    name='GeneralizedMatern'
)

In [26]:
from tensorflow_probability.substrates.jax.math.psd_kernels import MaternFiveHalves

In [32]:
k30=MaternFiveHalves(length_scale=0.5)
k30.matrix(X,Y)

Array([[0.84359044, 0.65835214, 0.85742986, ..., 0.88472855, 0.7736683 ,
        0.8832413 ],
       [0.82569665, 0.6063953 , 0.9138183 , ..., 0.90887076, 0.45159063,
        0.7123793 ],
       [0.69123787, 0.49951792, 0.7346841 , ..., 0.77887285, 0.9189904 ,
        0.93523484],
       ...,
       [0.2747652 , 0.24728283, 0.25762418, ..., 0.2722896 , 0.5199553 ,
        0.35344303],
       [0.51338255, 0.44937098, 0.48761648, ..., 0.50895923, 0.7139101 ,
        0.5891345 ],
       [0.24861957, 0.30660787, 0.20361732, ..., 0.20284304, 0.23273562,
        0.18961346]], dtype=float32)

In [29]:
from jax import grad

grad(k30.matrix,0)(X,Y)

TypeError: 'float' object is not iterable

In [22]:
k.batch_shape

TensorShape([])

In [30]:
k.matrix(X,Y)

Array([[0.85911628, 0.67949151, 0.8720622 , ..., 0.89736666, 0.79261181,
        0.89599651],
       [0.84226649, 0.62733218, 0.92396563, ..., 0.91947012, 0.4683715 ,
        0.73297514],
       [0.7121431 , 0.51809241, 0.7548131 , ..., 0.79762139, 0.92865248,
        0.9432827 ],
       ...,
       [0.28212326, 0.25293961, 0.26392352, ..., 0.27949535, 0.53916544,
        0.36542651],
       [0.53239708, 0.46605922, 0.50578406, ..., 0.52783747, 0.73447852,
        0.60985877],
       [0.25435943, 0.31589558, 0.20656687, ..., 0.20574526, 0.23748689,
        0.19171139]], dtype=float64)

In [33]:
k20=Differentiable_matern_kernel(3.4,0.5)
k20.apply('kappa', X, Y)

array([[0.85911734, 0.67949196, 0.87206335, ..., 0.89736779, 0.79261284,
        0.89599747],
       [0.84226768, 0.62733288, 0.92396665, ..., 0.91947101, 0.46837205,
        0.73297621],
       [0.71214374, 0.51809279, 0.75481367, ..., 0.7976221 , 0.92865316,
        0.94328359],
       ...,
       [0.28212358, 0.2529399 , 0.26392381, ..., 0.27949577, 0.53916604,
        0.36542689],
       [0.53239775, 0.46605959, 0.50578451, ..., 0.5278378 , 0.73447981,
        0.60985955],
       [0.25435978, 0.31589583, 0.20656716, ..., 0.20574547, 0.23748716,
        0.19171148]])

In [66]:
X1=np.random.rand(1000,2)
X2=np.random.rand(1000,2)

In [46]:

vmap(grad(lambda x1,x2,y1,y2:k_ex.apply([x1,x2],[y1,y2])))(X1[:,0],X1[:,1],X2[:,0],X2[:,1])

Array([ 0.77597547, -0.07441442,  0.86355537,  0.11294629, -0.09612498,
       -0.5733518 ,  0.83637446,  0.47536579, -0.35579169,  0.22175528,
       -0.80782914,  1.2054522 , -0.89258409, -0.19378771, -0.04883518,
        1.06471324,  1.23573315, -0.36742666, -0.51217258,  1.02113795,
        1.0319252 ,  0.46708742,  0.76188338,  0.3050577 ,  0.01572159,
        1.09000468, -0.09390831, -0.28227657,  0.79032683, -0.06031483,
       -0.73884451, -0.93737876,  0.38948923,  0.4206042 ,  0.85719001,
        0.54934597,  0.95941049,  0.77669746, -0.00263728,  0.24883346,
       -0.76897573,  0.63658738, -0.30916899,  0.54950851,  0.22706516,
       -0.0479443 ,  0.66254133, -0.42255116, -0.62988287, -0.18772092,
       -0.45460409,  1.08738863, -0.10607215, -0.75456697, -0.26568389,
       -0.66917574, -0.62131935, -0.9308359 ,  1.00316489, -0.12616596,
       -1.13137293, -0.61739022, -0.66051567, -0.65532649, -0.51242518,
       -0.3411411 ,  1.24541068, -0.08326506, -0.13999116,  0.41

In [67]:
k20.apply('D_x1_kappa', X1, X2)

array([[-0.32707158,  1.12360644,  1.17888534, ...,  0.84148288,
         0.86049014, -0.52097857],
       [-0.75209844, -0.39805204, -0.09727333, ..., -0.77744025,
        -0.85532057, -0.66511494],
       [-1.08764291,  0.04595311,  0.54051203, ..., -0.2148045 ,
        -0.06854504, -0.9204722 ],
       ...,
       [-0.71783906,  0.23821211,  0.99248153, ..., -0.1083087 ,
         0.12373343, -1.20152164],
       [-0.37738371,  0.93576169,  1.23880506, ...,  0.55043375,
         0.62735128, -0.80733526],
       [-0.30647376, -1.15268219, -0.13667963, ..., -0.99090517,
        -0.85033399, -0.89507163]])

In [42]:
k_ex=GeneralizedMatern(
            5/2,
            amplitude=None,
            length_scale=0.5,
            inverse_length_scale=None,
            feature_ndims=1,
            validate_args=False,
            name="GeneralizedMatern",
        )

In [63]:
k20=Differentiable_matern_kernel(5/2,0.5)


In [68]:
k20.apply('kappa', X1, X2)

array([[0.3751048 , 0.82786536, 0.5527889 , ..., 0.8446259 , 0.7672648 ,
        0.91501266],
       [0.28070432, 0.36462224, 0.4489014 , ..., 0.51035535, 0.5881613 ,
        0.29547626],
       [0.5429363 , 0.54790443, 0.5019019 , ..., 0.806995  , 0.8766817 ,
        0.611975  ],
       ...,
       [0.42412716, 0.8345645 , 0.7010329 , ..., 0.9971289 , 0.99511623,
        0.78058434],
       [0.3401162 , 0.90365833, 0.6384953 , ..., 0.8838121 , 0.8081853 ,
        0.8587605 ],
       [0.1413172 , 0.8255762 , 0.9904279 , ..., 0.64474624, 0.6292723 ,
        0.38570076]], dtype=float32)

In [69]:
k20.apply('kappa', X2, X2)

array([[1.        , 0.24127774, 0.16359754, ..., 0.41750526, 0.43376902,
        0.5467894 ],
       [0.24127774, 1.        , 0.84973013, ..., 0.856457  , 0.7994245 ,
        0.65492976],
       [0.16359754, 0.84973013, 1.        , ..., 0.70188916, 0.6916475 ,
        0.42119452],
       ...,
       [0.41750526, 0.856457  , 0.70188916, ..., 1.        , 0.9849938 ,
        0.8033087 ],
       [0.43376902, 0.7994245 , 0.6916475 , ..., 0.9849938 , 1.        ,
        0.74996984],
       [0.5467894 , 0.65492976, 0.42119452, ..., 0.8033087 , 0.74996984,
        1.        ]], dtype=float32)